### PR TITLE
Convert the codebase to ES6

### PR DESCRIPTION
**Pull request by ooflorent**

### CODE REVIEW

**Comment by sokra** [comment]
Thanks

**Comment by webmaster128** [comment]
Is node 6.11.5 a strict dependency? Or is 6.11.x sufficient?

**Comment by ooflorent** [comment]
@webmaster128 It is the same as webpack. See https://github.com/webpack/webpack/blob/213226ece261a0e89edb9de15fbc6775418f6041/package.json#L71

**Comment by montogeek** [comment]
According to http://node.green/ 6.4 would still be compatible (rest params, class, for..of)

**Pull request merged**
