### PR TITLE
removing tests from npm installations

### LINKED ISSUE #16: Flow complainis on `invalidPackageJson/package.json`
Hi, I'am truing out Flow, and have a problem with this module. Here what it is outputting:

```
$ flow 
Flow server launched for /Users/anon/projects/my/fluce
Spawned flow server (child pid=87549)
Logs will go to /var/folders/wt/s831gr6j4r38ffydyq0r2ft80000gn/T/flow/zSUserszSanonzSprojectszSmyzSfluce.log
The flow server will be ready in a moment.
Error: flow server is busyzing. If it was just started this can take some time. Retrying... |
Error: flow server is busyzing. If it was just started this can take some time. Retrying... -

/Users/anon/projects/my/fluce/node_modules/karma-webpack/node_modules/webpack/node_modules/enhanced-resolve/test/fixtures/node_modules/invalidPackageJson/package.json:1:3,2: Unexpected end of input

/Users/anon/projects/my/fluce/node_modules/webpack/node_modules/enhanced-resolve/test/fixtures/node_modules/invalidPackageJson/package.json:1:3,2: Unexpected end of input

Found 2 errors
```

As far as I understand, it scanning `/node_modules/` for some reason, and fails on your broken fixture module. Could you, perhaps, exclude tests from npm package, by adding them in `.npmignore`? If you could do that, that would be great!

### PR DESCRIPTION
**Pull request by bendman**
This fixes #16 by removing the tests folder from npm with an npmignore. I didn't include a version bump for package.json.

### CODE REVIEW

**Comment by bendman** [comment]
@sokra Is this an acceptable fix?

**Comment by sokra** [comment]
Could you use `package.json` `files` instead of `.npmignore`. That's a whitelist instead of a blacklist.

**Comment by sokra** [comment]
Thanks for the PR. I added the two lines in the package.json.

**Comment by bendman** [comment]
Ah, thank you for handling that.

**Pull request closed without merging**
