### PR TITLE
chore(deps): actually use graceful-fs

### PR DESCRIPTION
**Pull request by AviVahl**
Usage was removed at https://github.com/webpack/enhanced-resolve/pull/182

### CODE REVIEW

**Review by evilebottnawi — APPROVED** [review]
Good catch

**Review by sokra — CHANGES_REQUESTED** [review]
Good catch.

I think it was a mistake that this was removed.

This line

https://github.com/webpack/enhanced-resolve/blob/d6807b553dc7e3157746b57a82cb238cd5e58cee/lib/index.js#L8

should require graceful-fs instead.

Do you want to change that?

**Review by evilebottnawi — APPROVED** [review]

**Comment by AviVahl** [comment]
I changed it back per @sokra's comment.

TBH, as a *standalone* library, I would have expected enhanced-resolve to not use/require `graceful-fs` by default...
When used in `webpack`, it could have provided it with its own copy of `graceful-fs`... (via the `fileSystem` option)

**Comment by evilebottnawi** [comment]
Yep, we can improve it, but let's it do in the separate PR

**Review by sokra — APPROVED** [review]

**Comment by AviVahl** [comment]
@sokra this is ready for a merge, I guess...?

**Comment by sokra** [comment]
yes

**Comment by sokra** [comment]
thanks

**Pull request merged**
