### PR TITLE
support alias with a query

### PR DESCRIPTION
**Pull request by chinesedfan**
Enhanced #22.

Fixes  [#1289](https://github.com/webpack/webpack/issues/1289), [#1513](https://github.com/webpack/webpack/issues/1513), [#2465](https://github.com/webpack/webpack/issues/2465) in webpack.

### CODE REVIEW

**Comment by chinesedfan** [comment]
I don't know why this pr does not trigger the CI at first. So I close it and reopen.

**Comment by usirin** [comment]
Any update on this?

**Comment by sokra** [comment]
I cannot merge this, because it assumes that querystrings are always key-value pairs separated with `&`, but in fact it's up to the loader implementation to choose the format. They can use any string. And this is done in the wild.

**Comment by chinesedfan** [comment]
@sokra As loaders can use any string as the query string, is it impossible to implement this feature in fact?

**Comment by sokra** [comment]
yep. But you can write a custom resolver plugin (fork of the alias plugin), which implement this only for loaders that use this kind of querystrings

**Pull request closed without merging**
