### PR TITLE
Simplify it

### PR DESCRIPTION
**Pull request by GeassCoder**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Why you spam https://github.com/webpack/enhanced-resolve/pull/169?

**Comment by GeassCoder** [comment]
@evilebottnawi I signed the CLA but it still shows not signed yet. I'm not sure why yet, maybe I signed a name not matching my github account name, or my git config email is inconsistent with my github account email as I'm using company computer. 

I tried to fix it by updating the git config email locally, making a new branch and opening a new PR but it still doesn't work, then I realized the fact that the new branch still has the old commits with the old config email... Not sure what to do now.

**Comment by evilebottnawi** [comment]
@GeassCoder you commit contain another email, sue same email

**Comment by GeassCoder** [comment]
@evilebottnawi I have changed the config email, what should I do next? Should I rewrite those commits somehow?

**Comment by evilebottnawi** [comment]
All ok

**Comment by GeassCoder** [comment]
@evilebottnawi Thanks a lot! The CLA stuff is pretty new to me..

**Comment by GeassCoder** [comment]
> This is not a correct change.
> 
> `add` may not increase the count as the item could already be part of the Set.

Ah, I wish I had thought of this... Thanks for the explanation!

**Pull request closed without merging**
