### PR TITLE
Resolve `main` field as array for Bower

### LINKED ISSUE #3: Resolve main entry for bower and component
Hi!

I would like to see support out of the box in webpack for not only **npm**, but also the other very popular package managers, **bower** and **component**.

I'm guessing it should be a matter of adding this:
```javascript
new DirectoryDescriptionFilePlugin("package.json", ["main"]),
new DirectoryDescriptionFilePlugin("bower.json", ["main"]),
new DirectoryDescriptionFilePlugin("component.json", ["main"]),
```

Thank you!

### PR DESCRIPTION
**Pull request by mrm007**
Fixes #3 and webpack/webpack#143

### CODE REVIEW

**Comment by MrJH** [comment]
Why is this still open since november last year?

**Comment by swemaniac** [comment]
@MrJH I don't know but I got away with using this: https://github.com/lpiepiora/bower-webpack-plugin

**Comment by MrJH** [comment]
@swemaniac i'll give it a try next week, thx

**Comment by faller** [comment]
I tried

 new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main", ["main", 0]])

and

 new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])

but can't solve the problem.

https://github.com/lpiepiora/bower-webpack-plugin help a lot, thx!

**Pull request closed without merging**
