### PR TITLE
make eslint prettier to be compatible with CRLF and LF line break

### PR DESCRIPTION
**Pull request by Zuckjet**
[Fix](https://github.com/webpack/enhanced-resolve/issues/258)

### CODE REVIEW

**Review by evilebottnawi — COMMENTED** [review]
Why?

**Comment by Zuckjet** [comment]
> Why?

Linked a issue, do you think we should fix this ?

**Comment by evilebottnawi** [comment]
Yes

**Comment by Zuckjet** [comment]
@evilebottnawi  update prettier configuration as you suggested.

**Comment by evilebottnawi** [comment]
Just fix end of line of file, no need new options

**Comment by Zuckjet** [comment]
> Just fix end of line of file, no need new options

It turned out that it is my git client automatically convert LF to CRLF. I googled for a while, seems it is a weird behaviour on windows for a long history. Sorry for bothering

**Pull request closed without merging**
