### PR TITLE
Performance

### PR DESCRIPTION
**Pull request by sokra**

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Nice!  Is the performance gain from moving to using `Set` and `Map` instead of arrays and objects?

**Comment by sokra** [comment]
yes. This PR is a sum of many small changes.

**Comment by johnnyreilly** [comment]
Cool - something I'd like to move ts-loader to use Map - I didn't realize that could offer performance gains. Must take a look again

**Comment by sokra** [comment]
Currently Map is slower than using object for mapping for all operation except delete (afaik). Here delete is used. It depends on the usecase.

**Comment by sokra** [comment]
Also note that performance depends on node.js/v8 version. Older versions are slower with new ES6 stuff.

**Comment by johnnyreilly** [comment]
Ah cool - I might hold off a couple months then

**Pull request merged**
