### PR TITLE
enforce eslint require-hyphen-before-param-description

### PR DESCRIPTION
**Pull request by vankop**
Enforcing rule `jsdoc/require-hyphen-before-param-description` 

https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-require-hyphen-before-param-description

**What kind of change does this PR introduce?**

feature

**Did you add tests for your changes?**

No

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

Nothing

### CODE REVIEW

**Comment by vankop** [comment]
@evilebottnawi https://github.com/webpack/webpack/pull/9371#discussion_r301038233

**Comment by evilebottnawi** [comment]
:+1:

**Comment by sokra** [comment]
Thanks

**Comment by vankop** [comment]
> omg, that's great. I didn't know that this exists...
> 
> Do you want to enable this for webpack/webpack too?

Sure

**Pull request merged**
