### PR TITLE
Query to aliased resource with custom loader 

### PR DESCRIPTION
**Pull request by rpora**
Hi!

to resolve https://github.com/webpack/webpack/issues/1289

### CODE REVIEW

**Comment by Kreozot** [comment]
LGTM, please, check and merge!

**Comment by GreenGremlin** [comment]
Yes, please!

**Comment by qimingweng** [comment]
This is very much needed! Thank you :) 👍

**Comment by jharris4** [comment]
I'd love to see this fixed too!

**Comment by qimingweng** [comment]
@sokra Mentioned a few things that need to be done in this PR before it could be published here : https://github.com/webpack/webpack/issues/1513#issuecomment-162828395

**Pull request closed without merging**
