### PR TITLE
Update ResolverFactory.js

### PR DESCRIPTION
**Pull request by dlredden**
Issue #263 is preventing my company from upgrading to Webpack v5. This was the proposed fix that worked well for us so I created a PR.

### CODE REVIEW

**Comment by alexander-akait** [comment]
Please provide example how we can reproduce the problem

**Comment by ferdinando-ferreira** [comment]
> Please provide example how we can reproduce the problem

@alexander-akait : https://github.com/ferdinando-ferreira/enhanced-resolve-pnpapi-bug

```
git clone https://github.com/ferdinando-ferreira/enhanced-resolve-pnpapi-bug.git enhanced-resolve-pnpapi-bug
cd enhanced-resolve-pnpapi-bug
npm install
npm run build
```

**Comment by alexander-akait** [comment]
@ferdinando-ferreira Why do you bundle webpack? You should ignore this module (`resolve.fallback.pnpapi: false`) when you bundle webpack for browser, because browsers doesn't support pnp

**Comment by ferdinando-ferreira** [comment]
> Why do you bundle webpack?

@alexander-akait : To provide the minimal usecase requested. 

Regardless of usefulness it provides the exact error case reported:

`require("pnpapi")`

when it should be

`require("./PnpPlugin").PnpApiImpl`

because there is no pnpapi package.

Would you prefer a "realistic" use case that would hit the same error?

**Comment by alexander-akait** [comment]
Please read https://yarnpkg.com/advanced/pnpapi, "pnpapi" !== "require("./PnpPlugin").PnpApiImpl"

**Comment by ferdinando-ferreira** [comment]
> Please read https://yarnpkg.com/advanced/pnpapi, `require("pnpapi")` !== `require("./PnpPlugin").PnpApiImpl`

You are correct! The root cause of the error must be then the original issue submitter accidentally bundling something with a require to webpack (or other package depending on `enhanced-resolve`).

@dlredden, @dstampher: any chance that's the case?

**Comment by alexander-akait** [comment]
Yep, in this case `resolve.fallback.pnpapi: false` should solve the problem

**Comment by sokra** [comment]
It's not `resolve.fallback` but `externals` instead:

``` js
externals: {
  pnpapi: true
}
```

**Pull request closed without merging**
