### PR TITLE
#126: added LICENSE file

### LINKED ISSUE #126: Add License to repository
please add a LICENSE file to the repository.

### PR DESCRIPTION
**Pull request by aaronmallen**
resolves #126

### CODE REVIEW

**Comment by TheLarkInn** [comment]
@aaronmallen can you take a look at the Licenses of webpack/webpack, and webpack-contrib. Our license is slightly different (aka just the JS.Foundation license)

**Comment by aaronmallen** [comment]
So this is kind of why I submitted an issue vs a pr initially... I'll make the changes but in the future, I really do feel like a LICENSE for a project should be explicitly handled by the project owner/team.

**Comment by TheLarkInn** [comment]
Oh no worries whatsoever. It's great low hanging fruit for anyone! Thus the review process!!

**Comment by aaronmallen** [comment]
:+1:

**Pull request merged**
